name: Trigger auto deployment for mememinglebackend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mememinglebackend-AutoDeployTrigger-51dc33c6-d1a0-45e8-8393-d1c46353c6b4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MEMEMINGLEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEMEMINGLEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEMEMINGLEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}server
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: mememinglebackendregistry.azurecr.io
          registryUsername: ${{ secrets.MEMEMINGLEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEMEMINGLEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: mememinglebackend
          resourceGroup: hackathon
          imageToBuild: mememinglebackendregistry.azurecr.io/mememinglebackend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


